window.translations = {
  firstFeature: " ⚡ Rust Engine ",
  secondFeature: " 🔒 Offline First ",
  thirdFeature: " 🌎 Windows + macOS ",
  heroTitle1: "Compress More.",
  heroTitle2: "Save Space.",
  heroSub:
    "KENZ is a high-performance offline compression engine built with Rust and Zstandard. Shrink large projects, backups, and file collections without uploading your data anywhere.",
  downloadBtn: "↓ Download KENZ",
  seeFeaturesBtn: "See the features",
  applicationSize: "3 MB Application",
  losslessCompression: "Lossless Compression",
  version: "KENZ v1.2.1",
  archiveType: ".KENZ ARCHIVE",
  oldSize: " 28.00 GB ",
  originalLabel: "Original",
  compressedLabel: "Compressed",
  theWhy: "WHY KENZ",
  whyTitle: "Built for storage without compromise.",
  whySub:
    "A lightweight compression engine designed for developers and power users.",
  firstFeatureDesc:
    "Powered by Rust and Zstandard for efficient, high-speed local compression.",
  featureTag1: "ZSTD LEVELS 1-22",
  secondFeatureDesc:
    "Your files stay on your machine. No cloud uploads. No tracking.",
  featureTag2: "ZERO DATA TRANSFER",
  secondFeature: " 🔒 Offline First ",
  thirdFeature: " 🌎 Windows + macOS ",
  thirdFeatureDesc:
    "Designed for large projects, source code repositories, and thousands of files.",
  featureTag3: "LARGE DATASETS",
  realResults: "REAL RESULTS",
  seeSpace: "See the space KENZ saves.",
  benchmarkSub:
    "Real compression tests from large development and data directories.",
  savingResult: "STORAGE SAVED",
  smallerArchive: "smaller archive",
  projectType: "game project",
  zstdEngine: "ZSTD ENGINE",
  originalLabel: "Original",
  compressedLabel: "Compressed",
  archiveType: ".KENZ ARCHIVE",
  storageSaved: "STORAGE SAVED",
  projectType2: "Coding Folder",
  interactiveDemoTitle: "Interactive Demo",
  interactiveDemoSub: "Watch KENZ compress reality.",
  interactiveDemoDesc:
    "Click the project folder to simulate the high-speed Zstd compression engine in real-time.",
  folderNameDemo: "my_old_project",
  statusCard: "Engine Status",
  algorithmLabel: "Algorithm",
  compressionLabel: "Compression",
  filesProcessedLabel: "Files Processed",
  modeLabel: "Mode",
  modeOffline: "OFFLINE",
  levelPlaceholder: "LEVEL --",
  statusText: "Awaiting Input...",
  sectionTag: "Deep Capabilities",
  featuresTitle: "Built for storage without compromise.",
  featuresSub:
    "Explore the low-level architecture driving KENZ's lightning-fast local operations.",
  sidebarCompress: "Compress",
  sidebarDecompress: "Decompress",
  sidebarHistory: "History",
  sidebarSettings: "Settings",
  toastText: "Task completed successfully",
  statusReady: "ENGINE READY",
  statusText: "Awaiting local input directory payload...",
  featureWorkspace: "Workspace",
  featureDragDrop: "Fluid Drag & Drop Interception",
  featureDragDropDesc:
    "Bypass tedious system file picker menus. Drop massive developer project folders directly anywhere into the active window frame to capture and map paths instantly.",
  tauriTag: "Tauri Event Loop",
  payloadTag: "Payload Mapping",
  featureTwoTitle: "Interface Theme",
  featureTwoBigTitle: "Native Dark Workspace",
  featurTwoDesc:
    "A beautifully optimized dark palette engineered to reduce eye strain during late-night code archiving sessions. High contrast, sharp text, and zero UI stutter.",
  colorTag: "#0B0F19 Base",
  colorTagTwo: "Deep Contrast",
  featureBigThreeTitle: "Clean Light Workspace",
  featureThreeDesc:
    "Prefer crisp day rendering? Toggle instantly into a clean, fully light-mapped dashboard environment designed for daylight visibility without changing assets.",
  featureThreeFirstTag: "Daylight Crisp",
  featureThreeSecondTag: "CSS Variables",
  featureFourTitle: "Localization",
  featureBigFourTitle: "Tri-Language Dictionary Engine",
  featureFourDesc:
    "Switches between workspace interface languages natively. Instantly maps and renders every single label cleanly across comprehensive English, French, and Arabic setups.",
  FeatureFourFirstTag: "RTL Layout Support",
  FeatureFourSecondTag: "Local Dict Map",
  featureFiveTitle: "Analytics",
  featureFiveBigTitle: "Real-Time Storage Statistics",
  featureFiveDesc:
    "Track your data footprint metrics live. Compute exact compression ratios, storage saved over time, and active engine worker processing benchmarks instantly.",
  featureFiveTagOne: "SQLite Records",
  featureFiveTagTwo: "Ratio Telemetry",
  featureSixTitle: "Integrations",
  featureSixBigTitle: "Universal ZIP Support Layer",
  featureSixDesc:
    "Open fallback compatibility built natively. Packages compress in sequentially unrolled structures, ensuring anyone can view or extract them via standard WinRAR instantly.",
  featureSixFirstTag: "WinRAR Friendly",
  featureSixSecondTag: "Zero Lock-In",
  featureSevenTitle: "System Events",
  featureSevenBigTitle: "Asynchronous Task Notifications",
  featureSevenDesc:
    "Never sit staring at a progress bar. Receive immediate local popups and audio system toasts when a heavy multi-gigabyte compression pipeline finishes writing to storage.",
  featureSevenFirstTag: "Native System OS Toast",
  featureSevenSecondTag: "Async Tasks",
  piplelineTitle: "The Pipeline",
  pipelineSubTitle: "Three Steps. Absolute Control.",
  pipelineDesc:
    "No unnecessary steps or nested menus. Drop, tweak, and carry on with your workflow.",
  stepOneTitle: "Select or Drop",
  stepOneDesc:
    "Bypass tedious system file pickers entirely. Drag your heavy workspace folders straight into the dashboard loop interface to instantly map the file layout tree.",
  stepOneFirstTag: "Supports massive developer folders",
  stepOneSecondTag: "Instant layout discovery mapping",
  stepTwoTitle: "Choose Your Level",
  stepTwoDesc:
    "Fine-tune your output target with a slider. Dial it down to Level 1 for lightning-fast archiving speeds, or max it out to Level 22 for ultra-dense, maximum disk space recovery.",
  stepTwoFirstTag: "Levels 1–22 ZSTD Engine tuning",
  stepTwoSecondTag: "Adapts dynamically to system specs",
  stepThreeTitle: "Set It and Forget It",
  stepThreeDesc:
    "Hit compress and immediately switch back to your editor or regular tasks. The multi-threaded core runs silently in the background and drops a system notification the second it finishes.",
  stepThreeFirstTag: "Zero UI rendering stutter",
  stepThreeSecondTag: "Asynchronous native system toasts",
  showcaseTitle: "Interface Blueprint",
  showcaseSubTitle: "Explore the Desktop Workspace",
  showcaseDesc:
    "Take a closer look at the minimal, native interface built to handle your heavy storage workflows.",
  showcaseCompressTab: "Compress",
  showcaseDecompressTab: "Decompress",
  showcaseHistoryTab: "Statistics",
  showcaseSettingsTab: "Settings",
  pricingSectionTitle: "Fair Licensing",
  pricingSectionSubTitle: "Own Your Software. Permanently.",
  pricingSectionDesc:
    "No monthly SaaS drains. No mandatory cloud accounts. Pay once, use locally forever.",
  pricingSectionCardTitle: "🔥 Launch Offer",
  pricingFrameSubTitle: "Lifetime License",
  productPrice: "MAD",
  pricingPaymentNote: "One-time payment. Zero recurring subscriptions.",
  pricingClaimed: "8 / 10 Licenses Claimed",
  hurryPrice: "Price increases soon",
  proNumberOneTitle: "Lifetime Core Access",
  proNumberOneDesc:
    "Full permanent usage of the native Kenz desktop engine binaries.",
  proNumberTwoTitle: "All Future Engine Updates",
  proNumberTwoDesc:
    "Instant access to every upcoming optimization build layer without paying again.",
  proNumberThreeTitle: "100% Offline Local Control",
  proNumberThreeDesc:
    "Activates directly on your machine with zero remote cloud handshakes required.",
  pricingCta: "Secure Lifetime License",
  pricingCtaHelper: "🔒 Instant activation key delivered locally.",
  faqBigTitle: "Common Questions",
  faqTitle: "Frequently Asked Questions",
  faqSectionDesc:
    "Everything you need to know about the Kenz engine, licenses, and local operations.",
  firstQuestion: "How does the local lifetime license work?",
  firstAnswer:
    "It is a true one-time purchase. When you buy Kenz, you receive a license key to activate your local desktop application permanently. There are absolutely no monthly SaaS fees, cloud subscription traps, or recurring charges.",
  questionTwo: "Is my data sent to any external servers?",
  answerTwo:
    "Never. Kenz is built with a strict local-first, zero-knowledge architecture. It operates entirely offline on your computer, with all processing performed directly by your hardware. Your files and code never leave your machine.",
  questionThree:
    "What makes the Kenz ZSTD engine better than standard ZIP archives?",
  answerThree:
    "Standard ZIP compression is often limited by single-threaded performance. Kenz uses native Rust bindings to run parallel, multi-threaded Zstandard (ZSTD) compression, delivering significantly faster speeds, better compression ratios, and lower memory usage for large developer projects.",
  questionFour: "Can I extract my Kenz archives on other machines?",
  answerFour:
    "Yes! Although Kenz uses an optimized compression pipeline, the generated archives maintain standard structures. You can extract them on other computers using Kenz, WinRAR, 7-Zip, or other compatible archive software.",
  questionFive: "Does it support running alongside other tools in my workflow?",
  answerFive:
    "Absolutely. Kenz processes data efficiently in chunks to minimize memory usage, allowing you to compress large projects while continuing to code, run local servers, or build applications without slowing down your system.",
  ctaBigTitle: "GET INSTANT ACCESS",
  ctaTitle: "Run your archiving engine at full throttle.",
  ctaDesc:
    "Join the first wave of developers securing permanent, local drive space. Fast, multi-threaded, and 100% offline.",
  downloadWindows: "Download for Windows",
  downloadMacOs: "Download for macOS",
  systemRequirement: "Requires Windows 10 or 11 (64-bit Architecture)",
  brandName: "KENZ",
  brandTagline:
    "High-performance local archiving utility built natively in Rust.",
  websiteCopywrite: "© 2026 Kenz. All rights reserved.",
  websitePolicy: "Privacy First Policy",
  websiteLicense: "License Agreement",
};
