window.translations = {
  firstFeature: " ⚡ Moteur Rust ",
  secondFeature: " 🔒 Première Priorité Offline ",
  thirdFeature: " 🌎 Windows + macOS ",
  heroTitle1: "Compressez Plus.",
  heroTitle2: "Économisez de l'Espace.",
  heroSub:
    "KENZ est un moteur de compression hors ligne haute performance construit avec Rust et Zstandard. Réduisez la taille des grands projets, des sauvegardes et des collections de fichiers sans télécharger vos données nulle part.",
  downloadBtn: "↓ Télécharger KENZ",
  seeFeaturesBtn: "Voir les fonctionnalités",
  applicationSize: "3 MB Application",
  losslessCompression: "Compression Sans Perte",
  version: "KENZ v1.2.1",
  archiveType: ".ARCHIVE KENZ",
  oldSize: " 28.00 GB ",
  originalLabel: "Original",
  compressedLabel: "Compressé",
  theWhy: "POURQUOI KENZ",
  whyTitle: "Conçu pour le stockage sans compromis.",
  whySub:
    "Un moteur de compression léger conçu pour les développeurs et les utilisateurs avancés.",
  firstFeatureDesc:
    "Propulsé par Rust et Zstandard pour une compression locale efficace et rapide.",
  featureTag1: "NIVEAUX ZSTD 1-22",
  secondFeatureDesc:
    "Vos fichiers restent sur votre machine. Pas de téléchargements vers le cloud. Pas de suivi.",
  featureTag2: "ZÉRO TRANSFERT DE DONNÉES",
  thirdFeatureDesc:
    "Conçu pour les grands projets, les dépôts de code source et des milliers de fichiers.",
  featureTag3: "GRANDS ENSEMBLES DE DONNÉES",
  thirdFeature: " 🌎 Windows + macOS ",
  realResults: "RÉSULTATS RÉELS",
  seeSpace: "Voyez l'espace économisé par KENZ.",
  benchmarkSub:
    "Tests de compression réels sur des projets de développement et des répertoires de données volumineux.",
  savingResult: "ESPACE DE STOCKAGE ÉCONOMISÉ",
  smallerArchive: "archive plus petite",
  projectType: "projet de jeu",
  zstdEngine: "MOTEUR ZSTD",
  originalLabel: "Original",
  compressedLabel: "Compressé",
  archiveType: ".ARCHIVE KENZ",
  storageSaved: "ESPACCE DE STOCKAGE ÉCONOMISÉ",
  projectType2: "Dossier de Codage",
  interactiveDemoTitle: "Démo Interactive",
  interactiveDemoSub: "Voyez KENZ compresser la réalité.",
  interactiveDemoDesc:
    "Cliquez sur le dossier du projet pour simuler le moteur de compression Zstd à haute vitesse en temps réel.",
  folderNameDemo: "mon_ancien_projet",
  statusCard: "Statut du Moteur",
  algorithmLabel: "Algorithme",
  compressionLabel: "Compression",
  filesProcessedLabel: "Fichiers Traités",
  modeLabel: "Mode",
  modeOffline: "HORS LIGNE",
  levelPlaceholder: "NIVEAU --",
  statusText: "En attente d'entrée...",
  sectionTag: "Capacités Profondes",
  featuresTitle: "Conçu pour le stockage sans compromis.",
  featuresSub:
    "Explorez l'architecture de bas niveau qui fait de KENZ un moteur de compression local ultra-rapide.",
  sidebarCompress: "Compresser",
  sidebarDecompress: "Décompresser",
  sidebarHistory: "Historique",
  sidebarSettings: "Paramètres",
  toastText: "Tâche terminée avec succès",
  statusReady: "MOTEUR PRÊT",
  statusText: "En attente du répertoire d'entrée local...",
  featureWorkspace: "Espace de Travail",
  featureDragDrop: "Interception du Glissement et Dépôt Fluide",
  featureDragDropDesc:
    "Contournez les menus fastidieux du sélecteur de fichiers système. Déposez des dossiers de projets développeur massifs directement n'importe où dans le cadre de la fenêtre active pour capturer et cartographier les chemins instantanément.",
  tauriTag: "Boucle d'événements Tauri",
  payloadTag: "Mappage de la charge utile",
  featureTwoTitle: "Thème de l'interface",
  featureTwoBigTitle: "Espace de travail sombre natif",
  featurTwoDesc:
    "Une palette sombre magnifiquement optimisée, conçue pour réduire la fatigue oculaire lors des sessions nocturnes d'archivage de code. Contraste élevé, texte net et aucune saccade de l'interface.",
  colorTag: "#0B0F19 Base",
  colorTagTwo: "Contraste profond",
  featureBigThreeTitle: "Espace de travail clair et épuré",
  featureThreeDesc:
    "Vous préférez un affichage lumineux et net en journée ? Passez instantanément à un tableau de bord clair, entièrement optimisé pour la lumière, offrant une excellente visibilité sans modifier les ressources.",
  featureThreeFirstTag: "Clarté en plein jour",
  featureThreeSecondTag: "Variables CSS",
  featureFourTitle: "Localisation",
  featureBigFourTitle: "Moteur de dictionnaire trilingue",
  featureFourDesc:
    "Basculez nativement entre les langues de l'interface de l'espace de travail. Chaque libellé est instantanément traduit et affiché avec précision en anglais, en français et en arabe.",
  FeatureFourFirstTag: "Prise en charge RTL",
  FeatureFourSecondTag: "Dictionnaire local",
  featureFiveTitle: "Analyses",
  featureFiveBigTitle: "Statistiques de stockage en temps réel",
  featureFiveDesc:
    "Suivez en direct les métriques de votre espace de stockage. Calculez instantanément les taux de compression, l'espace économisé au fil du temps et les performances des processus actifs du moteur.",
  featureFiveTagOne: "Enregistrements SQLite",
  featureFiveTagTwo: "Télémétrie des ratios",
  featureSixTitle: "Intégrations",
  featureSixBigTitle: "Couche de prise en charge ZIP universelle",
  featureSixDesc:
    "Compatibilité ouverte intégrée nativement. Les archives sont compressées dans une structure standard, permettant à n'importe qui de les ouvrir ou de les extraire instantanément avec WinRAR ou tout autre logiciel compatible.",
  featureSixFirstTag: "Compatible WinRAR",
  featureSixSecondTag: "Aucun verrouillage",
  featureSevenTitle: "Événements système",
  featureSevenBigTitle: "Notifications des tâches asynchrones",
  featureSevenDesc:
    "Ne restez plus à attendre devant une barre de progression. Recevez instantanément des notifications locales et des alertes sonores lorsque la compression de fichiers volumineux est terminée et enregistrée sur le disque.",
  featureSevenFirstTag: "Notification système native",
  featureSevenSecondTag: "Tâches asynchrones",
  piplelineTitle: "Le pipeline",
  pipelineSubTitle: "Trois étapes. Contrôle absolu.",
  pipelineDesc:
    "Aucune étape inutile ni menu complexe. Déposez vos fichiers, ajustez les paramètres et poursuivez votre travail en toute simplicité.",
  stepOneTitle: "Sélectionner ou déposer",
  stepOneDesc:
    "Évitez complètement les sélecteurs de fichiers système fastidieux. Faites glisser vos dossiers de travail volumineux directement dans l'interface du tableau de bord pour cartographier instantanément l'arborescence des fichiers.",
  stepOneFirstTag: "Prend en charge les grands dossiers de développement",
  stepOneSecondTag: "Cartographie instantanée de la structure",
  stepTwoTitle: "Choisissez votre niveau",
  stepTwoDesc:
    "Ajustez précisément votre objectif de sortie avec un curseur. Réduisez-le au niveau 1 pour des vitesses d'archivage ultra-rapides, ou augmentez-le jusqu'au niveau 22 pour une compression maximale et une récupération optimale de l'espace disque.",
  stepTwoFirstTag: "Réglage du moteur ZSTD niveaux 1 à 22",
  stepTwoSecondTag: "S'adapte dynamiquement aux caractéristiques du système",
  stepThreeTitle: "Configurez et oubliez",
  stepThreeDesc:
    "Lancez la compression puis retournez immédiatement à votre éditeur ou à vos tâches habituelles. Le cœur multithreadé fonctionne silencieusement en arrière-plan et affiche une notification système dès qu'il termine.",
  stepThreeFirstTag: "Aucun ralentissement de l'interface",
  stepThreeSecondTag: "Notifications système natives asynchrones",
  showcaseTitle: "Plan de l'interface",
  showcaseSubTitle: "Découvrez l'espace de travail du bureau",
  showcaseDesc:
    "Découvrez de plus près l'interface native et minimaliste conçue pour gérer vos tâches de stockage intensives.",
  showcaseCompressTab: "Compresser",
  showcaseDecompressTab: "Décompresser",
  showcaseHistoryTab: "Statistiques",
  showcaseSettingsTab: "Paramètres",
  pricingSectionTitle: "Licence équitable",
  pricingSectionSubTitle: "Votre logiciel, pour toujours.",
  pricingSectionDesc:
    "Aucun abonnement mensuel. Aucun compte cloud obligatoire. Payez une seule fois et utilisez-le localement à vie.",
  pricingSectionCardTitle: "🔥 Offre de lancement",
  pricingFrameSubTitle: "Licence à vie",
  productPrice: "MAD",
  pricingPaymentNote: "Paiement unique. Aucun abonnement récurrent.",
  pricingClaimed: "8 / 10 licences réclamées",
  hurryPrice: "Le prix augmentera bientôt",
  proNumberOneTitle: "Accès au moteur à vie",
  proNumberOneDesc:
    "Utilisation permanente et complète des binaires natifs du moteur de bureau Kenz.",
  proNumberTwoTitle: "Toutes les futures mises à jour du moteur",
  proNumberTwoDesc:
    "Accès immédiat à toutes les futures optimisations du moteur, sans frais supplémentaires.",
  proNumberThreeTitle: "Contrôle local 100 % hors ligne",
  proNumberThreeDesc:
    "S'active directement sur votre ordinateur, sans aucune connexion ni authentification cloud requise.",
  pricingCta: "Obtenir une licence à vie",
  pricingCtaHelper: "🔒 Clé d'activation instantanée fournie localement.",
  faqBigTitle: "Questions courantes",
  faqTitle: "Questions fréquemment posées",
  faqSectionDesc:
    "Tout ce que vous devez savoir sur le moteur Kenz, les licences et son fonctionnement en local.",
  firstQuestion: "Comment fonctionne la licence locale à vie ?",
  firstAnswer:
    "Il s'agit d'un véritable achat unique. Après l'achat de Kenz, vous recevez une clé de licence qui active définitivement votre application de bureau. Aucun abonnement mensuel, aucun service SaaS ni frais récurrents.",
  questionTwo: "Mes données sont-elles envoyées vers des serveurs externes ?",
  answerTwo:
    "Jamais. Kenz repose sur une architecture locale et à connaissance nulle. Il fonctionne entièrement hors ligne sur votre ordinateur, où tous les traitements sont effectués directement par votre matériel. Vos fichiers et votre code ne quittent jamais votre machine.",
  questionThree:
    "Pourquoi le moteur ZSTD de Kenz est-il meilleur que les archives ZIP classiques ?",
  answerThree:
    "La compression ZIP classique est souvent limitée par un traitement mono-thread. Kenz utilise les liaisons natives Rust pour exécuter une compression Zstandard (ZSTD) parallèle et multithread, offrant des vitesses supérieures, de meilleurs taux de compression et une consommation mémoire réduite pour les projets volumineux.",
  questionFour: "Puis-je extraire mes archives Kenz sur d'autres ordinateurs ?",
  answerFour:
    "Oui ! Bien que Kenz utilise un pipeline de compression optimisé, les archives générées conservent une structure standard. Vous pouvez les extraire avec Kenz, WinRAR, 7-Zip ou tout autre logiciel compatible.",
  questionFive:
    "Puis-je utiliser Kenz en même temps que les autres outils de mon flux de travail ?",
  answerFive:
    "Absolument. Kenz traite les données par blocs afin de limiter l'utilisation de la mémoire, ce qui vous permet de compresser de gros projets tout en continuant à coder, exécuter des serveurs locaux ou compiler vos applications sans ralentissement.",
  ctaBigTitle: "ACCÈS IMMÉDIAT",
  ctaTitle: "Exploitez toute la puissance de votre moteur d'archivage.",
  ctaDesc:
    "Rejoignez les premiers développeurs à récupérer durablement de l'espace disque local. Rapide, multithread et 100 % hors ligne.",
  downloadWindows: "Télécharger pour Windows",
  downloadMacOs: "Télécharger pour macOS",
  systemRequirement: "Nécessite Windows 10 ou 11 (architecture 64 bits)",
  brandName: "KENZ",
  brandTagline:
    "Utilitaire d'archivage local haute performance développé nativement en Rust.",
  websiteCopywrite: "© 2026 Kenz. Tous droits réservés.",
  websitePolicy: "Politique de confidentialité",
  websiteLicense: "Contrat de licence",
};
