window.translations = {
  firstFeature: " ⚡ محرك Rust ",
  secondFeature: " 🔒  يعمل بدون اتصال بالإنترنت ",
  thirdFeature: " 🌎 ويندوز + macOS ",
  heroTitle1: "قم بالضغط أكثر.",
  heroTitle2: "احفظ المساحة.",
  heroSub:
    "KENZ هو محرك ضغط عالي الأداء مصمم للعمل دون اتصال بالإنترنت، مبني على Rust وZstandard. قم بتقليل حجم المشاريع والنسخ الاحتياطية والملفات دون رفع بياناتك إلى أي مكان.",
  seeFeaturesBtn: "عرض الميزات",
  downloadBtn: "↓ تحميل KENZ",
  applicationSize: "3 MB التطبيق",
  losslessCompression: "ضغط بدون فقدان",
  version: "KENZ v1.2.1",
  archiveType: ".KENZ أرشيف",
  oldSize: " 28.00 GB ",
  originalLabel: "الأصلية",
  compressedLabel: "المضغوطة",
  theWhy: "لماذا KENZ",
  whyTitle: "مصمم للتخزين دون تنازلات.",
  whySub: "محرك ضغط خفيف الوزن مصمم للمطورين والمستخدمين المتقدمين.",
  firstFeatureDesc: "مدعوم من Rust وZstandard لضغط محلي فعال وسريع.",
  featureTag1: "مستويات ZSTD 1-22",
  secondFeatureDesc:
    "ملفاتك تبقى على جهازك. لا رفع للملفات إلى السحابة. لا تتبع.",
  secondFeature: " 🔒  يعمل بدون اتصال بالإنترنت ",
  featureTag2: "لا نقل للبيانات",
  thirdFeature: " 🌎 ويندوز + macOS ",
  thirdFeatureDesc:
    "مصمم للمشاريع الكبيرة, مستودعات الكود المصدر, وآلاف الملفات.",
  featureTag3: "البيانات الكبيرة",
  realResults: "النتائج الحقيقية",
  seeSpace: "شاهد المساحة التي يوفرها KENZ.",
  benchmarkSub: "اختبارات ضغط حقيقية من مشاريع تطويرية كبيرة ودلائل بيانات.",
  savingResult: "المساحة المحفوظة",
  smallerArchive: "أرشيف أصغر",
  projectType: "مشروع لعبة",
  zstdEngine: "محرك ZSTD",
  originalLabel: "الأصلية",
  compressedLabel: "المضغوطة",
  archiveType: ".KENZ أرشيف",
  storageSaved: "المساحة المحفوظة",
  projectType2: "مجلد الترميز",
  interactiveDemoTitle: "العرض التوضيحي التفاعلي",
  interactiveDemoSub: "شاهد KENZ يضغط الواقع.",
  interactiveDemoDesc:
    "انقر على مجلد المشروع لمحاكاة محرك ضغط Zstd بسرعة عالية في الوقت الحقيقي.",
  folderNameDemo: "مشروعي_القديم",
  statusCard: "حالة المحرك",
  algorithmLabel: "الخوارزمية",
  compressionLabel: "الضغط",
  filesProcessedLabel: "الملفات المعالجة",
  modeLabel: "الوضع",
  modeOffline: "بدون اتصال بالإنترنت",
  levelPlaceholder: "المستوى --",
  statusText: "في انتظار الإدخال...",
  sectionTag: "قدرات عميقة",
  featuresTitle: "مصمم للتخزين دون تنازلات.",
  featuresSub:
    "استكشف البنية من المستوى المنخفض التي تجعل KENZ محركًا سريعًا للغاية للضغط المحلي.",
  sidebarCompress: "ضغط",
  sidebarDecompress: "فك الضغط",
  sidebarHistory: "التاريخ",
  sidebarSettings: "الإعدادات",
  toastText: "تمت المهمة بنجاح",
  statusReady: "المحرك جاهز",
  statusText: "في انتظار الإدخال...",
  featureWorkspace: "مساحة العمل",
  featureDragDrop: "اعتراض عمليات السحب والإفلات الانسيابية",
  featureDragDropDesc:
    "تجاوز قوائم النظام المملة لاختيار الملفات؛ إذ يمكنك سحب مجلدات مشاريع المطورين الضخمة وإفلاتها مباشرة في أي مكان داخل إطار النافذة النشطة لرصد المسارات وتحديدها على الفور.",
  tauriTag: "حلقة أحداث Tauri",
  payloadTag: "تعيين الحمولة",
  featureTwoTitle: "مظهر الواجهة",
  featureTwoBigTitle: "مساحة عمل داكنة أصلية",
  featurTwoDesc:
    "لوحة ألوان داكنة محسّنة بعناية لتقليل إجهاد العين أثناء جلسات أرشفة الأكواد الليلية. تباين عالٍ، نص واضح، وأداء سلس دون أي تقطيع.",
  colorTag: "قاعدة #0B0F19",
  colorTagTwo: "تباين عميق",
  featureBigThreeTitle: "مساحة عمل فاتحة ونظيفة",
  featureThreeDesc:
    "تفضل واجهة مشرقة وواضحة أثناء النهار؟ انتقل فورًا إلى بيئة لوحة تحكم فاتحة ومُحسّنة بالكامل لتوفير أفضل وضوح في الإضاءة الطبيعية دون تغيير الموارد.",
  featureThreeFirstTag: "وضوح نهاري",
  featureThreeSecondTag: "متغيرات CSS",
  featureFourTitle: "تعدد اللغات",
  featureBigFourTitle: "محرك القاموس ثلاثي اللغات",
  featureFourDesc:
    "يتيح التبديل بين لغات واجهة مساحة العمل بشكل أصلي، مع ترجمة وعرض جميع العناصر فورًا ودقة كاملة باللغات الإنجليزية والفرنسية والعربية.",
  FeatureFourFirstTag: "دعم تخطيط RTL",
  FeatureFourSecondTag: "قاموس محلي",
  featureFiveTitle: "التحليلات",
  featureFiveBigTitle: "إحصاءات التخزين في الوقت الفعلي",
  featureFiveDesc:
    "تابع مؤشرات استخدام مساحة التخزين بشكل مباشر. احسب نسب الضغط بدقة، والمساحة التي تم توفيرها مع مرور الوقت، وأداء عمليات محرك المعالجة النشطة فورًا.",
  featureFiveTagOne: "سجلات SQLite",
  featureFiveTagTwo: "قياس النسب",
  featureSixTitle: "التكاملات",
  featureSixBigTitle: "طبقة دعم ZIP الشاملة",
  featureSixDesc:
    "توافق مفتوح مدمج بشكل أصلي. يتم ضغط الحزم ببنية قياسية، مما يتيح لأي شخص عرضها أو استخراجها بسهولة باستخدام WinRAR أو أي برنامج متوافق آخر.",
  featureSixFirstTag: "متوافق مع WinRAR",
  featureSixSecondTag: "دون تقييد",
  featureSevenTitle: "أحداث النظام",
  featureSevenBigTitle: "إشعارات المهام غير المتزامنة",
  featureSevenDesc:
    "لا داعي للانتظار أمام شريط التقدم. استلم إشعارات منبثقة محلية وتنبيهات صوتية فور انتهاء عمليات الضغط الكبيرة متعددة الجيجابايت وحفظها على وحدة التخزين.",
  featureSevenFirstTag: "إشعارات النظام الأصلية",
  featureSevenSecondTag: "مهام غير متزامنة",
  piplelineTitle: "مسار العمل",
  pipelineSubTitle: "ثلاث خطوات. تحكم كامل.",
  pipelineDesc:
    "لا توجد خطوات غير ضرورية أو قوائم معقدة. أضف ملفاتك، عدّل الإعدادات، ثم واصل عملك بكل سهولة.",
  stepOneTitle: "اختر أو أسقط",
  stepOneDesc:
    "تجاوز نوافذ اختيار الملفات التقليدية المزعجة بالكامل. اسحب مجلدات العمل الكبيرة مباشرة إلى واجهة لوحة التحكم ليتم إنشاء خريطة لشجرة الملفات فورًا.",
  stepOneFirstTag: "يدعم مجلدات التطوير الضخمة",
  stepOneSecondTag: "اكتشاف فوري لبنية الملفات",
  stepTwoTitle: "اختر المستوى المناسب",
  stepTwoDesc:
    "اضبط مستوى الإخراج بدقة باستخدام شريط التمرير. اختر المستوى 1 للحصول على سرعة أرشفة فائقة، أو ارفعه إلى المستوى 22 للحصول على ضغط عالي الكثافة واستعادة أكبر قدر ممكن من مساحة القرص.",
  stepTwoFirstTag: "ضبط محرك ZSTD من المستوى 1 إلى 22",
  stepTwoSecondTag: "يتكيف تلقائيًا مع مواصفات النظام",
  stepThreeTitle: "اضبطه واتركه يعمل",
  stepThreeDesc:
    "ابدأ عملية الضغط ثم عد فورًا إلى محرر الأكواد أو مهامك اليومية. يعمل المحرك متعدد الخيوط بصمت في الخلفية ويرسل إشعارًا للنظام بمجرد الانتهاء.",
  stepThreeFirstTag: "بدون أي تقطيع في عرض الواجهة",
  stepThreeSecondTag: "إشعارات نظام أصلية غير متزامنة",
  showcaseTitle: "مخطط الواجهة",
  showcaseSubTitle: "استكشف مساحة عمل سطح المكتب",
  showcaseDesc:
    "ألقِ نظرة أقرب على الواجهة الأصلية والبسيطة المصممة للتعامل مع مهام التخزين الكبيرة.",
  showcaseCompressTab: "ضغط",
  showcaseDecompressTab: "فك الضغط",
  showcaseHistoryTab: "الإحصائيات",
  showcaseSettingsTab: "الإعدادات",
  pricingSectionTitle: "ترخيص عادل",
  pricingSectionSubTitle: "امتلك برنامجك إلى الأبد.",
  pricingSectionDesc:
    "لا اشتراكات شهرية مرهقة، ولا حسابات سحابية إلزامية. ادفع مرة واحدة واستخدمه محليًا مدى الحياة.",
  pricingSectionCardTitle: "🔥 عرض الإطلاق",
  pricingFrameSubTitle: "ترخيص مدى الحياة",
  productPrice: "درهم",
  pricingSectionTitle: "دفعة واحدة فقط. بدون أي اشتراكات متكررة.",
  pricingClaimed: "تم حجز 8 من أصل 10 تراخيص",
  hurryPrice: "سيرتفع السعر قريبًا",
  pricingPaymentNote: "دفع لمرة واحدة. لا توجد اشتراكات متكررة.",
  proNumberOneTitle: "وصول دائم إلى المحرك",
  proNumberOneDesc: "استخدام دائم وكامل لملفات محرك Kenz المكتبي الأصلية.",
  proNumberTwoTitle: "جميع تحديثات المحرك المستقبلية",
  proNumberTwoDesc:
    "احصل فورًا على جميع تحديثات وتحسينات المحرك القادمة دون أي رسوم إضافية.",
  proNumberThreeTitle: "تحكم محلي 100% دون اتصال",
  proNumberThreeDesc:
    "يتم التفعيل مباشرة على جهازك دون الحاجة إلى أي اتصال أو مصادقة عبر السحابة.",
  pricingCta: "احصل على ترخيص مدى الحياة",
  pricingCtaHelper: "🔒 يتم تسليم مفتاح التفعيل فورًا على جهازك.",
  faqBigTitle: "الأسئلة الشائعة",
  faqTitle: "الأسئلة المتكررة",
  faqSectionDesc:
    "كل ما تحتاج إلى معرفته حول محرك Kenz والتراخيص وطريقة عمله محليًا.",
  firstQuestion: "كيف يعمل الترخيص المحلي مدى الحياة؟",
  firstAnswer:
    "إنه شراء لمرة واحدة فقط. عند شراء Kenz ستحصل على مفتاح ترخيص يفعّل تطبيق سطح المكتب على جهازك بشكل دائم. لا توجد أي اشتراكات شهرية أو رسوم متكررة أو خدمات سحابية إلزامية.",
  questionTwo: "هل يتم إرسال بياناتي إلى أي خوادم خارجية؟",
  answerTwo:
    "أبدًا. يعتمد Kenz على بنية محلية بالكامل ونهج انعدام المعرفة. يعمل دون اتصال بالإنترنت، وتتم جميع عمليات المعالجة مباشرة على جهازك، ولا تغادر ملفاتك أو أكوادك جهازك مطلقًا.",
  questionThree: "ما الذي يجعل محرك Kenz ZSTD أفضل من أرشيفات ZIP التقليدية؟",
  answerThree:
    "يعتمد ضغط ZIP التقليدي غالبًا على معالجة أحادية الخيط، بينما يستخدم Kenz ربطًا أصليًا بلغة Rust لتشغيل ضغط Zstandard (ZSTD) متعدد الخيوط بشكل متوازٍ، مما يوفر سرعة أعلى ونسبة ضغط أفضل واستهلاكًا أقل للذاكرة عند التعامل مع المشاريع الكبيرة.",
  questionFour: "هل يمكنني استخراج أرشيفات Kenz على أجهزة أخرى؟",
  answerFour:
    "نعم. رغم أن Kenz يستخدم آلية ضغط محسنة، فإن الملفات الناتجة تحافظ على بنية قياسية، ويمكن استخراجها باستخدام Kenz أو WinRAR أو 7-Zip أو أي برنامج متوافق آخر.",
  questionFive:
    "هل يمكن تشغيله إلى جانب الأدوات الأخرى ضمن سير العمل الخاص بي؟",
  answerFive:
    "بالتأكيد. يعالج Kenz البيانات على دفعات لتقليل استهلاك الذاكرة، مما يتيح لك ضغط المشاريع الكبيرة مع الاستمرار في كتابة الأكواد أو تشغيل الخوادم المحلية أو بناء التطبيقات دون التأثير على أداء النظام.",
  ctaBigTitle: "احصل على وصول فوري",
  ctaTitle: "شغّل محرك الأرشفة بكامل طاقته.",
  ctaDesc:
    "انضم إلى أوائل المطورين الذين يستعيدون مساحة التخزين المحلية بشكل دائم. سريع، متعدد الخيوط، ويعمل دون اتصال بالإنترنت بنسبة 100٪.",
  downloadWindows: "تنزيل لنظام Windows",
  downloadMacOs: "تنزيل لنظام macOS",
  systemRequirement: "يتطلب Windows 10 أو Windows 11 (بنية 64 بت)",
  brandName: "KENZ",
  brandTagline: "أداة أرشفة محلية عالية الأداء، مطورة بلغة Rust الأصلية.",
  websiteCopywrite: "© 2026 Kenz. جميع الحقوق محفوظة.",
  websitePolicy: "سياسة الخصوصية أولًا",
  websiteLicense: "اتفاقية الترخيص",
};
